on: [push]
name: Build & Push Container Image

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Build with Gradle
          run: ./gradlew build

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.AZURE_CLIENT_ID }}
            password: ${{ secrets.AZURE_CLIENT_SECRET }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/java-demo:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/java-demo:${{ github.sha }}
