on: [push]
name: Build & Push Container Image

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout GitHub Action
          uses: actions/checkout@main

        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Build with Gradle
          run: ./gradlew build

        - name: Login via Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}
            acrName: az204acraemdb
            containerAppName: java-demo
            resourceGroup: RG1
            containerAppEnvironment: Java-Demo-Environment
